config:
  title: MWE test app

main_controller:
  type: base
  #kwargs: ...

sources:
  main:
    type: table


views:
  dataframe:
    type: dataframe
    source: main

control_panels:
  - file_input
