config:
  title: Multi Scatter App

main_controller:
  type: base

sources:
  main:
    type: table


opts:
  scatter_opt:
    type: generic
    framewise: True
    xlabel: Position
    ylabel: Value
    show_legend: False

views:
  xy_scatter:
    type: hvplot
    source: main
    kind: scatter
    opts:
      - scatter_opt


control_panels:
  - scatter
